FROM 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-tensorflow-serving:1.12.0-cpu

ADD ./requirements.inference.txt /opt/requirements.txt

RUN pip3 install -r /opt/requirements.txt

ADD ./inference.py /opt/inference.py

CMD ["FLASK_APP=${PWD}/inference.py flask run --host 0.0.0.0 --port 8080"]